//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicalUserInterfaceLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphicalUserInterfaceLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string Button_AddFriend {
            get {
                return ResourceManager.GetString("Button_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string Button_EditProfile {
            get {
                return ResourceManager.GetString("Button_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game settings.
        /// </summary>
        public static string Button_GameSetting {
            get {
                return ResourceManager.GetString("Button_GameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New game.
        /// </summary>
        public static string Button_NewGame {
            get {
                return ResourceManager.GetString("Button_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unfriend.
        /// </summary>
        public static string Button_Unfriend {
            get {
                return ResourceManager.GetString("Button_Unfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View profile.
        /// </summary>
        public static string Button_ViewProfile {
            get {
                return ResourceManager.GetString("Button_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess.
        /// </summary>
        public static string Game_Button_Guess {
            get {
                return ResourceManager.GetString("Game_Button_Guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave game.
        /// </summary>
        public static string Game_Button_LeaveGame {
            get {
                return ResourceManager.GetString("Game_Button_LeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clues.
        /// </summary>
        public static string Game_Label_Clues {
            get {
                return ResourceManager.GetString("Game_Label_Clues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave this game?.
        /// </summary>
        public static string Game_Label_LeaveConfirmation {
            get {
                return ResourceManager.GetString("Game_Label_LeaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporting player: .
        /// </summary>
        public static string Game_Label_ReportingPlayer {
            get {
                return ResourceManager.GetString("Game_Label_ReportingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score: .
        /// </summary>
        public static string Game_Label_Score {
            get {
                return ResourceManager.GetString("Game_Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string General_Button_Accept {
            get {
                return ResourceManager.GetString("General_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string General_Button_Cancel {
            get {
                return ResourceManager.GetString("General_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string General_Button_No {
            get {
                return ResourceManager.GetString("General_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string General_Button_Report {
            get {
                return ResourceManager.GetString("General_Button_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View profile.
        /// </summary>
        public static string General_Button_ViewProfile {
            get {
                return ResourceManager.GetString("General_Button_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string General_Button_Yes {
            get {
                return ResourceManager.GetString("General_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string General_Label_Email {
            get {
                return ResourceManager.GetString("General_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This e-mail is already in our system.
        /// </summary>
        public static string General_Label_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("General_Label_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid e-mail address.
        /// </summary>
        public static string General_Label_EmailInvalid {
            get {
                return ResourceManager.GetString("General_Label_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string General_Label_Password {
            get {
                return ResourceManager.GetString("General_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your password.
        /// </summary>
        public static string General_Label_PasswordConfirmation {
            get {
                return ResourceManager.GetString("General_Label_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords must match.
        /// </summary>
        public static string General_Label_PasswordDontMatch {
            get {
                return ResourceManager.GetString("General_Label_PasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password.
        /// </summary>
        public static string General_Label_PasswordInvalid {
            get {
                return ResourceManager.GetString("General_Label_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string General_Label_Username {
            get {
                return ResourceManager.GetString("General_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid username.
        /// </summary>
        public static string General_Label_UsernameInvalid {
            get {
                return ResourceManager.GetString("General_Label_UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Label_Friends {
            get {
                return ResourceManager.GetString("Label_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games played.
        /// </summary>
        public static string Label_GamesPlayed {
            get {
                return ResourceManager.GetString("Label_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string Label_GamesWon {
            get {
                return ResourceManager.GetString("Label_GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string Label_InviteFriend {
            get {
                return ResourceManager.GetString("Label_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player description.
        /// </summary>
        public static string Label_PlayerDescription {
            get {
                return ResourceManager.GetString("Label_PlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player ID.
        /// </summary>
        public static string Label_PlayerID {
            get {
                return ResourceManager.GetString("Label_PlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player level.
        /// </summary>
        public static string Label_PlayerLevel {
            get {
                return ResourceManager.GetString("Label_PlayerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player profile.
        /// </summary>
        public static string Label_PlayerProfile {
            get {
                return ResourceManager.GetString("Label_PlayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rank.
        /// </summary>
        public static string Label_PlayerRank {
            get {
                return ResourceManager.GetString("Label_PlayerRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search player.
        /// </summary>
        public static string Label_SearchPlayer {
            get {
                return ResourceManager.GetString("Label_SearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string LogIn_Button_ForgotYourPassword {
            get {
                return ResourceManager.GetString("LogIn_Button_ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your e-mail address. If we have it on our system, we´ll send you instructions to re-establish your password..
        /// </summary>
        public static string LogIn_Label_PasswordRecovery1 {
            get {
                return ResourceManager.GetString("LogIn_Label_PasswordRecovery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We sent you an e-mail to: .
        /// </summary>
        public static string LogIn_Label_PasswordRecovery2 {
            get {
                return ResourceManager.GetString("LogIn_Label_PasswordRecovery2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string LogIn_LogIn {
            get {
                return ResourceManager.GetString("LogIn_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string LogIn_PlayAsGuest {
            get {
                return ResourceManager.GetString("LogIn_PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string LogIn_SignUp {
            get {
                return ResourceManager.GetString("LogIn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
