//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string Button_AddFriend {
            get {
                return ResourceManager.GetString("Button_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Button_EditProfile {
            get {
                return ResourceManager.GetString("Button_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string Button_GameSetting {
            get {
                return ResourceManager.GetString("Button_GameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string Button_NewGame {
            get {
                return ResourceManager.GetString("Button_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriend.
        /// </summary>
        public static string Button_Unfriend {
            get {
                return ResourceManager.GetString("Button_Unfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string Button_ViewProfile {
            get {
                return ResourceManager.GetString("Button_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it, have &lt;b&gt;fun :D&lt;/b&gt;.
        /// </summary>
        public static string Email_SignUpWelcome_Body {
            get {
                return ResourceManager.GetString("Email_SignUpWelcome_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Crosswords.
        /// </summary>
        public static string Email_SignUpWelcome_Header {
            get {
                return ResourceManager.GetString("Email_SignUpWelcome_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up to Crosswords!.
        /// </summary>
        public static string Email_SignUpWelcome_Subject {
            get {
                return ResourceManager.GetString("Email_SignUpWelcome_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t reach our servers. Please, try again later..
        /// </summary>
        public static string Exception_ServerFailure {
            get {
                return ResourceManager.GetString("Exception_ServerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess.
        /// </summary>
        public static string Game_Button_Guess {
            get {
                return ResourceManager.GetString("Game_Button_Guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave game.
        /// </summary>
        public static string Game_Button_LeaveGame {
            get {
                return ResourceManager.GetString("Game_Button_LeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clues.
        /// </summary>
        public static string Game_Label_Clues {
            get {
                return ResourceManager.GetString("Game_Label_Clues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this game?.
        /// </summary>
        public static string Game_Label_LeaveConfirmation {
            get {
                return ResourceManager.GetString("Game_Label_LeaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting player: .
        /// </summary>
        public static string Game_Label_ReportingPlayer {
            get {
                return ResourceManager.GetString("Game_Label_ReportingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: .
        /// </summary>
        public static string Game_Label_Score {
            get {
                return ResourceManager.GetString("Game_Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string General_Button_Accept {
            get {
                return ResourceManager.GetString("General_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Button_Cancel {
            get {
                return ResourceManager.GetString("General_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_Button_No {
            get {
                return ResourceManager.GetString("General_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string General_Button_Report {
            get {
                return ResourceManager.GetString("General_Button_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string General_Button_ViewProfile {
            get {
                return ResourceManager.GetString("General_Button_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Button_Yes {
            get {
                return ResourceManager.GetString("General_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string General_Label_Email {
            get {
                return ResourceManager.GetString("General_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already in our system.
        /// </summary>
        public static string General_Label_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("General_Label_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        public static string General_Label_EmailInvalid {
            get {
                return ResourceManager.GetString("General_Label_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Label_Password {
            get {
                return ResourceManager.GetString("General_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string General_Label_PasswordConfirmation {
            get {
                return ResourceManager.GetString("General_Label_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must match.
        /// </summary>
        public static string General_Label_PasswordDontMatch {
            get {
                return ResourceManager.GetString("General_Label_PasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string General_Label_PasswordInvalid {
            get {
                return ResourceManager.GetString("General_Label_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string General_Label_Username {
            get {
                return ResourceManager.GetString("General_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string General_Label_UsernameInvalid {
            get {
                return ResourceManager.GetString("General_Label_UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Label_Friends {
            get {
                return ResourceManager.GetString("Label_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played.
        /// </summary>
        public static string Label_GamesPlayed {
            get {
                return ResourceManager.GetString("Label_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won.
        /// </summary>
        public static string Label_GamesWon {
            get {
                return ResourceManager.GetString("Label_GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friend.
        /// </summary>
        public static string Label_InviteFriend {
            get {
                return ResourceManager.GetString("Label_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player description.
        /// </summary>
        public static string Label_PlayerDescription {
            get {
                return ResourceManager.GetString("Label_PlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player ID.
        /// </summary>
        public static string Label_PlayerID {
            get {
                return ResourceManager.GetString("Label_PlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player level.
        /// </summary>
        public static string Label_PlayerLevel {
            get {
                return ResourceManager.GetString("Label_PlayerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player profile.
        /// </summary>
        public static string Label_PlayerProfile {
            get {
                return ResourceManager.GetString("Label_PlayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Label_PlayerRank {
            get {
                return ResourceManager.GetString("Label_PlayerRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search player.
        /// </summary>
        public static string Label_SearchPlayer {
            get {
                return ResourceManager.GetString("Label_SearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string LogIn_Button_ForgotYourPassword {
            get {
                return ResourceManager.GetString("LogIn_Button_ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn_Button_Login {
            get {
                return ResourceManager.GetString("LogIn_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as guest.
        /// </summary>
        public static string LogIn_Button_PlayAsGuest {
            get {
                return ResourceManager.GetString("LogIn_Button_PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn_LogIn {
            get {
                return ResourceManager.GetString("LogIn_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as guest.
        /// </summary>
        public static string LogIn_PlayAsGuest {
            get {
                return ResourceManager.GetString("LogIn_PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LogIn_SignUp {
            get {
                return ResourceManager.GetString("LogIn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up. Have fun!.
        /// </summary>
        public static string Message_SignUpSuccess {
            get {
                return ResourceManager.GetString("Message_SignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string RecoverPassword_Button_Recover {
            get {
                return ResourceManager.GetString("RecoverPassword_Button_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email:.
        /// </summary>
        public static string RecoverPassword_Label_Email {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username:.
        /// </summary>
        public static string RecoverPassword_Label_Username {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Your Password.
        /// </summary>
        public static string RecoverPassword_RecoverYourPassword {
            get {
                return ResourceManager.GetString("RecoverPassword_RecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address and username. If we have it on our system, we´ll send you instructions to re-establish your password..
        /// </summary>
        public static string RecoverPassword_TextBlock_RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPassword_TextBlock_RecoverPasswordMessage", resourceCulture);
            }
        }
    }
}
