//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLayer.ServicesImplementation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool credentialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool credential {
            get {
                return this.credentialField;
            }
            set {
                if ((this.credentialField.Equals(value) != true)) {
                    this.credentialField = value;
                    this.RaisePropertyChanged("credential");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUserType {
            get {
                return this.idUserTypeField;
            }
            set {
                if ((this.idUserTypeField.Equals(value) != true)) {
                    this.idUserTypeField = value;
                    this.RaisePropertyChanged("idUserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Players", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Players : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.ProfileImages ProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Ranks RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Users UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gamesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string playerDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int playerLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string playerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string playerRankField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.ProfileImages ProfileImage {
            get {
                return this.ProfileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageField, value) != true)) {
                    this.ProfileImageField = value;
                    this.RaisePropertyChanged("ProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Ranks Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Users User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gamesPlayed {
            get {
                return this.gamesPlayedField;
            }
            set {
                if ((this.gamesPlayedField.Equals(value) != true)) {
                    this.gamesPlayedField = value;
                    this.RaisePropertyChanged("gamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gamesWon {
            get {
                return this.gamesWonField;
            }
            set {
                if ((this.gamesWonField.Equals(value) != true)) {
                    this.gamesWonField = value;
                    this.RaisePropertyChanged("gamesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfileImage {
            get {
                return this.idProfileImageField;
            }
            set {
                if ((this.idProfileImageField.Equals(value) != true)) {
                    this.idProfileImageField = value;
                    this.RaisePropertyChanged("idProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRank {
            get {
                return this.idRankField;
            }
            set {
                if ((this.idRankField.Equals(value) != true)) {
                    this.idRankField = value;
                    this.RaisePropertyChanged("idRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string playerDescription {
            get {
                return this.playerDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.playerDescriptionField, value) != true)) {
                    this.playerDescriptionField = value;
                    this.RaisePropertyChanged("playerDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int playerLevel {
            get {
                return this.playerLevelField;
            }
            set {
                if ((this.playerLevelField.Equals(value) != true)) {
                    this.playerLevelField = value;
                    this.RaisePropertyChanged("playerLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string playerName {
            get {
                return this.playerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.playerNameField, value) != true)) {
                    this.playerNameField = value;
                    this.RaisePropertyChanged("playerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string playerRank {
            get {
                return this.playerRankField;
            }
            set {
                if ((object.ReferenceEquals(this.playerRankField, value) != true)) {
                    this.playerRankField = value;
                    this.RaisePropertyChanged("playerRank");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileImages", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class ProfileImages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profileImageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfileImage {
            get {
                return this.idProfileImageField;
            }
            set {
                if ((this.idProfileImageField.Equals(value) != true)) {
                    this.idProfileImageField = value;
                    this.RaisePropertyChanged("idProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profileImageName {
            get {
                return this.profileImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.profileImageNameField, value) != true)) {
                    this.profileImageNameField = value;
                    this.RaisePropertyChanged("profileImageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ranks", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Ranks : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rankPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRank {
            get {
                return this.idRankField;
            }
            set {
                if ((this.idRankField.Equals(value) != true)) {
                    this.idRankField = value;
                    this.RaisePropertyChanged("idRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rankName {
            get {
                return this.rankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.rankNameField, value) != true)) {
                    this.rankNameField = value;
                    this.RaisePropertyChanged("rankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rankPoints {
            get {
                return this.rankPointsField;
            }
            set {
                if ((this.rankPointsField.Equals(value) != true)) {
                    this.rankPointsField = value;
                    this.RaisePropertyChanged("rankPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Categories : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Reports[] ReportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Reports[] Reports {
            get {
                return this.ReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsField, value) != true)) {
                    this.ReportsField = value;
                    this.RaisePropertyChanged("Reports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategory {
            get {
                return this.idCategoryField;
            }
            set {
                if ((this.idCategoryField.Equals(value) != true)) {
                    this.idCategoryField = value;
                    this.RaisePropertyChanged("idCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reports", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Reports : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Categories CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Users UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chatLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Categories Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Users User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chatLog {
            get {
                return this.chatLogField;
            }
            set {
                if ((object.ReferenceEquals(this.chatLogField, value) != true)) {
                    this.chatLogField = value;
                    this.RaisePropertyChanged("chatLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategory {
            get {
                return this.idCategoryField;
            }
            set {
                if ((this.idCategoryField.Equals(value) != true)) {
                    this.idCategoryField = value;
                    this.RaisePropertyChanged("idCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReport {
            get {
                return this.idReportField;
            }
            set {
                if ((this.idReportField.Equals(value) != true)) {
                    this.idReportField = value;
                    this.RaisePropertyChanged("idReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GamesPlayers", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class GamesPlayers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Games GameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Players PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gameRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gameScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hasTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idGameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Games Game {
            get {
                return this.GameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameField, value) != true)) {
                    this.GameField = value;
                    this.RaisePropertyChanged("Game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Players Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gameRank {
            get {
                return this.gameRankField;
            }
            set {
                if ((this.gameRankField.Equals(value) != true)) {
                    this.gameRankField = value;
                    this.RaisePropertyChanged("gameRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gameScore {
            get {
                return this.gameScoreField;
            }
            set {
                if ((this.gameScoreField.Equals(value) != true)) {
                    this.gameScoreField = value;
                    this.RaisePropertyChanged("gameScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hasTurn {
            get {
                return this.hasTurnField;
            }
            set {
                if ((this.hasTurnField.Equals(value) != true)) {
                    this.hasTurnField = value;
                    this.RaisePropertyChanged("hasTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idGame {
            get {
                return this.idGameField;
            }
            set {
                if ((this.idGameField.Equals(value) != true)) {
                    this.idGameField = value;
                    this.RaisePropertyChanged("idGame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Games", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Games : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.GamesPlayers[] GamesPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime gameDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan gameTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idGameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.GamesPlayers[] GamesPlayers {
            get {
                return this.GamesPlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesPlayersField, value) != true)) {
                    this.GamesPlayersField = value;
                    this.RaisePropertyChanged("GamesPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime gameDate {
            get {
                return this.gameDateField;
            }
            set {
                if ((this.gameDateField.Equals(value) != true)) {
                    this.gameDateField = value;
                    this.RaisePropertyChanged("gameDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan gameTime {
            get {
                return this.gameTimeField;
            }
            set {
                if ((this.gameTimeField.Equals(value) != true)) {
                    this.gameTimeField = value;
                    this.RaisePropertyChanged("gameTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idGame {
            get {
                return this.idGameField;
            }
            set {
                if ((this.idGameField.Equals(value) != true)) {
                    this.idGameField = value;
                    this.RaisePropertyChanged("idGame");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordsBoard", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class WordsBoard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Boards BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Word WordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte xEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte xStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte yEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte yStartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Boards Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Word Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBoard {
            get {
                return this.idBoardField;
            }
            set {
                if ((this.idBoardField.Equals(value) != true)) {
                    this.idBoardField = value;
                    this.RaisePropertyChanged("idBoard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idWord {
            get {
                return this.idWordField;
            }
            set {
                if ((this.idWordField.Equals(value) != true)) {
                    this.idWordField = value;
                    this.RaisePropertyChanged("idWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte xEnd {
            get {
                return this.xEndField;
            }
            set {
                if ((this.xEndField.Equals(value) != true)) {
                    this.xEndField = value;
                    this.RaisePropertyChanged("xEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte xStart {
            get {
                return this.xStartField;
            }
            set {
                if ((this.xStartField.Equals(value) != true)) {
                    this.xStartField = value;
                    this.RaisePropertyChanged("xStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte yEnd {
            get {
                return this.yEndField;
            }
            set {
                if ((this.yEndField.Equals(value) != true)) {
                    this.yEndField = value;
                    this.RaisePropertyChanged("yEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte yStart {
            get {
                return this.yStartField;
            }
            set {
                if ((this.yStartField.Equals(value) != true)) {
                    this.yStartField = value;
                    this.RaisePropertyChanged("yStart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boards", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Boards : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.WordsBoard[] WordsBoardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string boardMatrixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBoardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.WordsBoard[] WordsBoards {
            get {
                return this.WordsBoardsField;
            }
            set {
                if ((object.ReferenceEquals(this.WordsBoardsField, value) != true)) {
                    this.WordsBoardsField = value;
                    this.RaisePropertyChanged("WordsBoards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string boardMatrix {
            get {
                return this.boardMatrixField;
            }
            set {
                if ((object.ReferenceEquals(this.boardMatrixField, value) != true)) {
                    this.boardMatrixField = value;
                    this.RaisePropertyChanged("boardMatrix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBoard {
            get {
                return this.idBoardField;
            }
            set {
                if ((this.idBoardField.Equals(value) != true)) {
                    this.idBoardField = value;
                    this.RaisePropertyChanged("idBoard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.WordsBoard[] WordsBoardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string termField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.WordsBoard[] WordsBoards {
            get {
                return this.WordsBoardsField;
            }
            set {
                if ((object.ReferenceEquals(this.WordsBoardsField, value) != true)) {
                    this.WordsBoardsField = value;
                    this.RaisePropertyChanged("WordsBoards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clue {
            get {
                return this.clueField;
            }
            set {
                if ((object.ReferenceEquals(this.clueField, value) != true)) {
                    this.clueField = value;
                    this.RaisePropertyChanged("clue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSolved {
            get {
                return this.isSolvedField;
            }
            set {
                if ((this.isSolvedField.Equals(value) != true)) {
                    this.isSolvedField = value;
                    this.RaisePropertyChanged("isSolved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string term {
            get {
                return this.termField;
            }
            set {
                if ((object.ReferenceEquals(this.termField, value) != true)) {
                    this.termField = value;
                    this.RaisePropertyChanged("term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class GameConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Boards BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> GamePlayerQueueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnSecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFLayer.ServicesImplementation.Users[] UsersRoomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Boards Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> GamePlayerQueue {
            get {
                return this.GamePlayerQueueField;
            }
            set {
                if ((object.ReferenceEquals(this.GamePlayerQueueField, value) != true)) {
                    this.GamePlayerQueueField = value;
                    this.RaisePropertyChanged("GamePlayerQueue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnAmount {
            get {
                return this.TurnAmountField;
            }
            set {
                if ((this.TurnAmountField.Equals(value) != true)) {
                    this.TurnAmountField = value;
                    this.RaisePropertyChanged("TurnAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnSeconds {
            get {
                return this.TurnSecondsField;
            }
            set {
                if ((this.TurnSecondsField.Equals(value) != true)) {
                    this.TurnSecondsField = value;
                    this.RaisePropertyChanged("TurnSeconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFLayer.ServicesImplementation.Users[] UsersRoom {
            get {
                return this.UsersRoomField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersRoomField, value) != true)) {
                    this.UsersRoomField = value;
                    this.RaisePropertyChanged("UsersRoom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesImplementation.IUsersManager", CallbackContract=typeof(WPFLayer.ServicesImplementation.IUsersManagerCallback))]
    public interface IUsersManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/AddUser", ReplyAction="http://tempuri.org/IUsersManager/AddUserResponse")]
        bool AddUser(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/AddUser", ReplyAction="http://tempuri.org/IUsersManager/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/FindUserByEmail", ReplyAction="http://tempuri.org/IUsersManager/FindUserByEmailResponse")]
        bool FindUserByEmail(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/FindUserByEmail", ReplyAction="http://tempuri.org/IUsersManager/FindUserByEmailResponse")]
        System.Threading.Tasks.Task<bool> FindUserByEmailAsync(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/Login", ReplyAction="http://tempuri.org/IUsersManager/LoginResponse")]
        WPFLayer.ServicesImplementation.Players Login(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/Login", ReplyAction="http://tempuri.org/IUsersManager/LoginResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> LoginAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RecoverPassword", ReplyAction="http://tempuri.org/IUsersManager/RecoverPasswordResponse")]
        bool RecoverPassword(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RecoverPassword", ReplyAction="http://tempuri.org/IUsersManager/RecoverPasswordResponse")]
        System.Threading.Tasks.Task<bool> RecoverPasswordAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RegisterRecoveredPassword", ReplyAction="http://tempuri.org/IUsersManager/RegisterRecoveredPasswordResponse")]
        bool RegisterRecoveredPassword(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RegisterRecoveredPassword", ReplyAction="http://tempuri.org/IUsersManager/RegisterRecoveredPasswordResponse")]
        System.Threading.Tasks.Task<bool> RegisterRecoveredPasswordAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetPlayerInformation", ReplyAction="http://tempuri.org/IUsersManager/GetPlayerInformationResponse")]
        WPFLayer.ServicesImplementation.Players GetPlayerInformation(WPFLayer.ServicesImplementation.Players player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetPlayerInformation", ReplyAction="http://tempuri.org/IUsersManager/GetPlayerInformationResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> GetPlayerInformationAsync(WPFLayer.ServicesImplementation.Players player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetReportCategories", ReplyAction="http://tempuri.org/IUsersManager/GetReportCategoriesResponse")]
        WPFLayer.ServicesImplementation.Categories[] GetReportCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetReportCategories", ReplyAction="http://tempuri.org/IUsersManager/GetReportCategoriesResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Categories[]> GetReportCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RegisterReport", ReplyAction="http://tempuri.org/IUsersManager/RegisterReportResponse")]
        bool RegisterReport(WPFLayer.ServicesImplementation.Reports report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/RegisterReport", ReplyAction="http://tempuri.org/IUsersManager/RegisterReportResponse")]
        System.Threading.Tasks.Task<bool> RegisterReportAsync(WPFLayer.ServicesImplementation.Reports report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetUserByPlayer", ReplyAction="http://tempuri.org/IUsersManager/GetUserByPlayerResponse")]
        WPFLayer.ServicesImplementation.Users GetUserByPlayer(WPFLayer.ServicesImplementation.Players player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/GetUserByPlayer", ReplyAction="http://tempuri.org/IUsersManager/GetUserByPlayerResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Users> GetUserByPlayerAsync(WPFLayer.ServicesImplementation.Players player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersManager/Response", ReplyAction="http://tempuri.org/IUsersManager/ResponseResponse")]
        void Response([System.ServiceModel.MessageParameterAttribute(Name="response")] bool response1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersManagerChannel : WPFLayer.ServicesImplementation.IUsersManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersManagerClient : System.ServiceModel.DuplexClientBase<WPFLayer.ServicesImplementation.IUsersManager>, WPFLayer.ServicesImplementation.IUsersManager {
        
        public UsersManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UsersManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UsersManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UsersManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UsersManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool AddUser(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public bool FindUserByEmail(string userEmail) {
            return base.Channel.FindUserByEmail(userEmail);
        }
        
        public System.Threading.Tasks.Task<bool> FindUserByEmailAsync(string userEmail) {
            return base.Channel.FindUserByEmailAsync(userEmail);
        }
        
        public WPFLayer.ServicesImplementation.Players Login(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> LoginAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.LoginAsync(user);
        }
        
        public bool RecoverPassword(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RecoverPassword(user);
        }
        
        public System.Threading.Tasks.Task<bool> RecoverPasswordAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RecoverPasswordAsync(user);
        }
        
        public bool RegisterRecoveredPassword(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RegisterRecoveredPassword(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterRecoveredPasswordAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RegisterRecoveredPasswordAsync(user);
        }
        
        public WPFLayer.ServicesImplementation.Players GetPlayerInformation(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetPlayerInformation(player);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> GetPlayerInformationAsync(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetPlayerInformationAsync(player);
        }
        
        public WPFLayer.ServicesImplementation.Categories[] GetReportCategories() {
            return base.Channel.GetReportCategories();
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Categories[]> GetReportCategoriesAsync() {
            return base.Channel.GetReportCategoriesAsync();
        }
        
        public bool RegisterReport(WPFLayer.ServicesImplementation.Reports report) {
            return base.Channel.RegisterReport(report);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterReportAsync(WPFLayer.ServicesImplementation.Reports report) {
            return base.Channel.RegisterReportAsync(report);
        }
        
        public WPFLayer.ServicesImplementation.Users GetUserByPlayer(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetUserByPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Users> GetUserByPlayerAsync(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetUserByPlayerAsync(player);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesImplementation.IPlayersManagement")]
    public interface IPlayersManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetFriendList", ReplyAction="http://tempuri.org/IPlayersManagement/GetFriendListResponse")]
        WPFLayer.ServicesImplementation.Players[] GetFriendList(WPFLayer.ServicesImplementation.Players player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetFriendList", ReplyAction="http://tempuri.org/IPlayersManagement/GetFriendListResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players[]> GetFriendListAsync(WPFLayer.ServicesImplementation.Players player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayersManagement/RegisterPlayerResponse")]
        WPFLayer.ServicesImplementation.Players RegisterPlayer(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayersManagement/RegisterPlayerResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> RegisterPlayerAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetPlayerFor", ReplyAction="http://tempuri.org/IPlayersManagement/GetPlayerForResponse")]
        WPFLayer.ServicesImplementation.Players GetPlayerFor(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetPlayerFor", ReplyAction="http://tempuri.org/IPlayersManagement/GetPlayerForResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> GetPlayerForAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetFilteredPlayers", ReplyAction="http://tempuri.org/IPlayersManagement/GetFilteredPlayersResponse")]
        WPFLayer.ServicesImplementation.Players[] GetFilteredPlayers(string nameFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/GetFilteredPlayers", ReplyAction="http://tempuri.org/IPlayersManagement/GetFilteredPlayersResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players[]> GetFilteredPlayersAsync(string nameFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/AddFriend", ReplyAction="http://tempuri.org/IPlayersManagement/AddFriendResponse")]
        bool AddFriend(WPFLayer.ServicesImplementation.Players playerOrigin, WPFLayer.ServicesImplementation.Players playerTarget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayersManagement/AddFriend", ReplyAction="http://tempuri.org/IPlayersManagement/AddFriendResponse")]
        System.Threading.Tasks.Task<bool> AddFriendAsync(WPFLayer.ServicesImplementation.Players playerOrigin, WPFLayer.ServicesImplementation.Players playerTarget);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayersManagementChannel : WPFLayer.ServicesImplementation.IPlayersManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayersManagementClient : System.ServiceModel.ClientBase<WPFLayer.ServicesImplementation.IPlayersManagement>, WPFLayer.ServicesImplementation.IPlayersManagement {
        
        public PlayersManagementClient() {
        }
        
        public PlayersManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayersManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFLayer.ServicesImplementation.Players[] GetFriendList(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetFriendList(player);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players[]> GetFriendListAsync(WPFLayer.ServicesImplementation.Players player) {
            return base.Channel.GetFriendListAsync(player);
        }
        
        public WPFLayer.ServicesImplementation.Players RegisterPlayer(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RegisterPlayer(user);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> RegisterPlayerAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.RegisterPlayerAsync(user);
        }
        
        public WPFLayer.ServicesImplementation.Players GetPlayerFor(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.GetPlayerFor(user);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players> GetPlayerForAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.GetPlayerForAsync(user);
        }
        
        public WPFLayer.ServicesImplementation.Players[] GetFilteredPlayers(string nameFilter) {
            return base.Channel.GetFilteredPlayers(nameFilter);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Players[]> GetFilteredPlayersAsync(string nameFilter) {
            return base.Channel.GetFilteredPlayersAsync(nameFilter);
        }
        
        public bool AddFriend(WPFLayer.ServicesImplementation.Players playerOrigin, WPFLayer.ServicesImplementation.Players playerTarget) {
            return base.Channel.AddFriend(playerOrigin, playerTarget);
        }
        
        public System.Threading.Tasks.Task<bool> AddFriendAsync(WPFLayer.ServicesImplementation.Players playerOrigin, WPFLayer.ServicesImplementation.Players playerTarget) {
            return base.Channel.AddFriendAsync(playerOrigin, playerTarget);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesImplementation.IGameManagement", CallbackContract=typeof(WPFLayer.ServicesImplementation.IGameManagementCallback))]
    public interface IGameManagement {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SendSolvedWordsBoard")]
        void SendSolvedWordsBoard(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayersQueue, WPFLayer.ServicesImplementation.GamesPlayers solver, WPFLayer.ServicesImplementation.WordsBoard solvedWordsBoard);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SendSolvedWordsBoard")]
        System.Threading.Tasks.Task SendSolvedWordsBoardAsync(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayersQueue, WPFLayer.ServicesImplementation.GamesPlayers solver, WPFLayer.ServicesImplementation.WordsBoard solvedWordsBoard);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/JoinGame")]
        void JoinGame(WPFLayer.ServicesImplementation.GamesPlayers gamePlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/JoinGame")]
        System.Threading.Tasks.Task JoinGameAsync(WPFLayer.ServicesImplementation.GamesPlayers gamePlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/PassTurn")]
        void PassTurn(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers, int currentTurns);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/PassTurn")]
        System.Threading.Tasks.Task PassTurnAsync(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers, int currentTurns);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/EndGame")]
        void EndGame(int idRoom, WPFLayer.ServicesImplementation.GamesPlayers[] playerRanks);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/EndGame")]
        System.Threading.Tasks.Task EndGameAsync(int idRoom, WPFLayer.ServicesImplementation.GamesPlayers[] playerRanks);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/RemovePlayer")]
        void RemovePlayer(WPFLayer.ServicesImplementation.Players leavingPlayer, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/RemovePlayer")]
        System.Threading.Tasks.Task RemovePlayerAsync(WPFLayer.ServicesImplementation.Players leavingPlayer, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/RemoveHost")]
        void RemoveHost(WPFLayer.ServicesImplementation.GamesPlayers host, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/RemoveHost")]
        System.Threading.Tasks.Task RemoveHostAsync(WPFLayer.ServicesImplementation.GamesPlayers host, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ReceiveSolvedWordsBoard")]
        void ReceiveSolvedWordsBoard(WPFLayer.ServicesImplementation.GamesPlayers solver, WPFLayer.ServicesImplementation.WordsBoard solvedWordsBoard);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ReceiveTurn")]
        void ReceiveTurn();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/UpdateGamePlayersQueue")]
        void UpdateGamePlayersQueue(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers, int remainingTurns);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ShowPlayerRanks")]
        void ShowPlayerRanks(WPFLayer.ServicesImplementation.GamesPlayers[] playerRanks);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/RemoveLeavingUser")]
        void RemoveLeavingUser(WPFLayer.ServicesImplementation.Players leavingPlayer, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> updatedQueue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SendLeavingUserToMainMenu")]
        void SendLeavingUserToMainMenu();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/StopGame")]
        void StopGame();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagementChannel : WPFLayer.ServicesImplementation.IGameManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagementClient : System.ServiceModel.DuplexClientBase<WPFLayer.ServicesImplementation.IGameManagement>, WPFLayer.ServicesImplementation.IGameManagement {
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendSolvedWordsBoard(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayersQueue, WPFLayer.ServicesImplementation.GamesPlayers solver, WPFLayer.ServicesImplementation.WordsBoard solvedWordsBoard) {
            base.Channel.SendSolvedWordsBoard(gamePlayersQueue, solver, solvedWordsBoard);
        }
        
        public System.Threading.Tasks.Task SendSolvedWordsBoardAsync(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayersQueue, WPFLayer.ServicesImplementation.GamesPlayers solver, WPFLayer.ServicesImplementation.WordsBoard solvedWordsBoard) {
            return base.Channel.SendSolvedWordsBoardAsync(gamePlayersQueue, solver, solvedWordsBoard);
        }
        
        public void JoinGame(WPFLayer.ServicesImplementation.GamesPlayers gamePlayer) {
            base.Channel.JoinGame(gamePlayer);
        }
        
        public System.Threading.Tasks.Task JoinGameAsync(WPFLayer.ServicesImplementation.GamesPlayers gamePlayer) {
            return base.Channel.JoinGameAsync(gamePlayer);
        }
        
        public void PassTurn(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers, int currentTurns) {
            base.Channel.PassTurn(gamePlayers, currentTurns);
        }
        
        public System.Threading.Tasks.Task PassTurnAsync(System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers, int currentTurns) {
            return base.Channel.PassTurnAsync(gamePlayers, currentTurns);
        }
        
        public void EndGame(int idRoom, WPFLayer.ServicesImplementation.GamesPlayers[] playerRanks) {
            base.Channel.EndGame(idRoom, playerRanks);
        }
        
        public System.Threading.Tasks.Task EndGameAsync(int idRoom, WPFLayer.ServicesImplementation.GamesPlayers[] playerRanks) {
            return base.Channel.EndGameAsync(idRoom, playerRanks);
        }
        
        public void RemovePlayer(WPFLayer.ServicesImplementation.Players leavingPlayer, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers) {
            base.Channel.RemovePlayer(leavingPlayer, gamePlayers);
        }
        
        public System.Threading.Tasks.Task RemovePlayerAsync(WPFLayer.ServicesImplementation.Players leavingPlayer, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers) {
            return base.Channel.RemovePlayerAsync(leavingPlayer, gamePlayers);
        }
        
        public void RemoveHost(WPFLayer.ServicesImplementation.GamesPlayers host, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers) {
            base.Channel.RemoveHost(host, gamePlayers);
        }
        
        public System.Threading.Tasks.Task RemoveHostAsync(WPFLayer.ServicesImplementation.GamesPlayers host, System.Collections.Generic.Queue<WPFLayer.ServicesImplementation.GamesPlayers> gamePlayers) {
            return base.Channel.RemoveHostAsync(host, gamePlayers);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesImplementation.IGameRoomManagement", CallbackContract=typeof(WPFLayer.ServicesImplementation.IGameRoomManagementCallback))]
    public interface IGameRoomManagement {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/SendInvitationToRoom")]
        void SendInvitationToRoom(int idRoom, WPFLayer.ServicesImplementation.Users userTarget);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/SendInvitationToRoom")]
        System.Threading.Tasks.Task SendInvitationToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users userTarget);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/JoinToRoom")]
        void JoinToRoom(int idRoom, WPFLayer.ServicesImplementation.Users newUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/JoinToRoom")]
        System.Threading.Tasks.Task JoinToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/CheckRoomAvailability", ReplyAction="http://tempuri.org/IGameRoomManagement/CheckRoomAvailabilityResponse")]
        bool CheckRoomAvailability(int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/CheckRoomAvailability", ReplyAction="http://tempuri.org/IGameRoomManagement/CheckRoomAvailabilityResponse")]
        System.Threading.Tasks.Task<bool> CheckRoomAvailabilityAsync(int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/CreateRoom", ReplyAction="http://tempuri.org/IGameRoomManagement/CreateRoomResponse")]
        int CreateRoom(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/CreateRoom", ReplyAction="http://tempuri.org/IGameRoomManagement/CreateRoomResponse")]
        System.Threading.Tasks.Task<int> CreateRoomAsync(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/ConnectGameRoomManagement", ReplyAction="http://tempuri.org/IGameRoomManagement/ConnectGameRoomManagementResponse")]
        void ConnectGameRoomManagement(WPFLayer.ServicesImplementation.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/ConnectGameRoomManagement", ReplyAction="http://tempuri.org/IGameRoomManagement/ConnectGameRoomManagementResponse")]
        System.Threading.Tasks.Task ConnectGameRoomManagementAsync(WPFLayer.ServicesImplementation.Users users);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/ExitToRoom")]
        void ExitToRoom(int idRoom, WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/ExitToRoom")]
        System.Threading.Tasks.Task ExitToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/DeleteRoom")]
        void DeleteRoom(int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/DeleteRoom")]
        System.Threading.Tasks.Task DeleteRoomAsync(int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/LaunchGamePage")]
        void LaunchGamePage(WPFLayer.ServicesImplementation.GameConfiguration gameConfiguration, int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameRoomManagement/LaunchGamePage")]
        System.Threading.Tasks.Task LaunchGamePageAsync(WPFLayer.ServicesImplementation.GameConfiguration gameConfiguration, int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/GetBoardById", ReplyAction="http://tempuri.org/IGameRoomManagement/GetBoardByIdResponse")]
        WPFLayer.ServicesImplementation.Boards GetBoardById(int idBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/GetBoardById", ReplyAction="http://tempuri.org/IGameRoomManagement/GetBoardByIdResponse")]
        System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Boards> GetBoardByIdAsync(int idBoard);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameRoomManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/ReciveInvitationToRoom", ReplyAction="http://tempuri.org/IGameRoomManagement/ReciveInvitationToRoomResponse")]
        void ReciveInvitationToRoom(int idRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/UpdateRoom", ReplyAction="http://tempuri.org/IGameRoomManagement/UpdateRoomResponse")]
        void UpdateRoom(WPFLayer.ServicesImplementation.Users[] usersInRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/ForceExitToRoom", ReplyAction="http://tempuri.org/IGameRoomManagement/ForceExitToRoomResponse")]
        void ForceExitToRoom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameRoomManagement/EnterGame", ReplyAction="http://tempuri.org/IGameRoomManagement/EnterGameResponse")]
        void EnterGame(WPFLayer.ServicesImplementation.GameConfiguration gameConfiguration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameRoomManagementChannel : WPFLayer.ServicesImplementation.IGameRoomManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameRoomManagementClient : System.ServiceModel.DuplexClientBase<WPFLayer.ServicesImplementation.IGameRoomManagement>, WPFLayer.ServicesImplementation.IGameRoomManagement {
        
        public GameRoomManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameRoomManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameRoomManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameRoomManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameRoomManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendInvitationToRoom(int idRoom, WPFLayer.ServicesImplementation.Users userTarget) {
            base.Channel.SendInvitationToRoom(idRoom, userTarget);
        }
        
        public System.Threading.Tasks.Task SendInvitationToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users userTarget) {
            return base.Channel.SendInvitationToRoomAsync(idRoom, userTarget);
        }
        
        public void JoinToRoom(int idRoom, WPFLayer.ServicesImplementation.Users newUser) {
            base.Channel.JoinToRoom(idRoom, newUser);
        }
        
        public System.Threading.Tasks.Task JoinToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users newUser) {
            return base.Channel.JoinToRoomAsync(idRoom, newUser);
        }
        
        public bool CheckRoomAvailability(int idRoom) {
            return base.Channel.CheckRoomAvailability(idRoom);
        }
        
        public System.Threading.Tasks.Task<bool> CheckRoomAvailabilityAsync(int idRoom) {
            return base.Channel.CheckRoomAvailabilityAsync(idRoom);
        }
        
        public int CreateRoom(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.CreateRoom(user);
        }
        
        public System.Threading.Tasks.Task<int> CreateRoomAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.CreateRoomAsync(user);
        }
        
        public void ConnectGameRoomManagement(WPFLayer.ServicesImplementation.Users users) {
            base.Channel.ConnectGameRoomManagement(users);
        }
        
        public System.Threading.Tasks.Task ConnectGameRoomManagementAsync(WPFLayer.ServicesImplementation.Users users) {
            return base.Channel.ConnectGameRoomManagementAsync(users);
        }
        
        public void ExitToRoom(int idRoom, WPFLayer.ServicesImplementation.Users user) {
            base.Channel.ExitToRoom(idRoom, user);
        }
        
        public System.Threading.Tasks.Task ExitToRoomAsync(int idRoom, WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.ExitToRoomAsync(idRoom, user);
        }
        
        public void DeleteRoom(int idRoom) {
            base.Channel.DeleteRoom(idRoom);
        }
        
        public System.Threading.Tasks.Task DeleteRoomAsync(int idRoom) {
            return base.Channel.DeleteRoomAsync(idRoom);
        }
        
        public void LaunchGamePage(WPFLayer.ServicesImplementation.GameConfiguration gameConfiguration, int idRoom) {
            base.Channel.LaunchGamePage(gameConfiguration, idRoom);
        }
        
        public System.Threading.Tasks.Task LaunchGamePageAsync(WPFLayer.ServicesImplementation.GameConfiguration gameConfiguration, int idRoom) {
            return base.Channel.LaunchGamePageAsync(gameConfiguration, idRoom);
        }
        
        public WPFLayer.ServicesImplementation.Boards GetBoardById(int idBoard) {
            return base.Channel.GetBoardById(idBoard);
        }
        
        public System.Threading.Tasks.Task<WPFLayer.ServicesImplementation.Boards> GetBoardByIdAsync(int idBoard) {
            return base.Channel.GetBoardByIdAsync(idBoard);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesImplementation.IMessages", CallbackContract=typeof(WPFLayer.ServicesImplementation.IMessagesCallback))]
    public interface IMessages {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessages/SendChatMessage")]
        void SendChatMessage(WPFLayer.ServicesImplementation.Users[] room, WPFLayer.ServicesImplementation.Users userOrigin, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessages/SendChatMessage")]
        System.Threading.Tasks.Task SendChatMessageAsync(WPFLayer.ServicesImplementation.Users[] room, WPFLayer.ServicesImplementation.Users userOrigin, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessages/SendPrivateMessage")]
        void SendPrivateMessage(WPFLayer.ServicesImplementation.Users userOrigin, WPFLayer.ServicesImplementation.Users userDestination, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessages/SendPrivateMessage")]
        System.Threading.Tasks.Task SendPrivateMessageAsync(WPFLayer.ServicesImplementation.Users userOrigin, WPFLayer.ServicesImplementation.Users userDestination, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessages/ConnectMessages", ReplyAction="http://tempuri.org/IMessages/ConnectMessagesResponse")]
        void ConnectMessages(WPFLayer.ServicesImplementation.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessages/ConnectMessages", ReplyAction="http://tempuri.org/IMessages/ConnectMessagesResponse")]
        System.Threading.Tasks.Task ConnectMessagesAsync(WPFLayer.ServicesImplementation.Users user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagesCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessages/ReciveChatMessage")]
        void ReciveChatMessage(WPFLayer.ServicesImplementation.Users userOrigin, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagesChannel : WPFLayer.ServicesImplementation.IMessages, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagesClient : System.ServiceModel.DuplexClientBase<WPFLayer.ServicesImplementation.IMessages>, WPFLayer.ServicesImplementation.IMessages {
        
        public MessagesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MessagesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MessagesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendChatMessage(WPFLayer.ServicesImplementation.Users[] room, WPFLayer.ServicesImplementation.Users userOrigin, string message) {
            base.Channel.SendChatMessage(room, userOrigin, message);
        }
        
        public System.Threading.Tasks.Task SendChatMessageAsync(WPFLayer.ServicesImplementation.Users[] room, WPFLayer.ServicesImplementation.Users userOrigin, string message) {
            return base.Channel.SendChatMessageAsync(room, userOrigin, message);
        }
        
        public void SendPrivateMessage(WPFLayer.ServicesImplementation.Users userOrigin, WPFLayer.ServicesImplementation.Users userDestination, string message) {
            base.Channel.SendPrivateMessage(userOrigin, userDestination, message);
        }
        
        public System.Threading.Tasks.Task SendPrivateMessageAsync(WPFLayer.ServicesImplementation.Users userOrigin, WPFLayer.ServicesImplementation.Users userDestination, string message) {
            return base.Channel.SendPrivateMessageAsync(userOrigin, userDestination, message);
        }
        
        public void ConnectMessages(WPFLayer.ServicesImplementation.Users user) {
            base.Channel.ConnectMessages(user);
        }
        
        public System.Threading.Tasks.Task ConnectMessagesAsync(WPFLayer.ServicesImplementation.Users user) {
            return base.Channel.ConnectMessagesAsync(user);
        }
    }
}
