//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrosswordsContext : DbContext
    {
        public CrosswordsContext()
            : base("name=CrosswordsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<GamesPlayer> GamesPlayers { get; set; }
        public virtual DbSet<Board> Boards { get; set; }
        public virtual DbSet<WordsBoard> WordsBoards { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
