//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Report
    {
        public int idReport { get; set; }
        public int idUser { get; set; }
        public int idCategory { get; set; }
        public string chatLog { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
