//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WordsBoard
    {
        public int idWord { get; set; }
        public int idBoard { get; set; }
        public byte xStart { get; set; }
        public byte xEnd { get; set; }
        public byte yStart { get; set; }
        public byte yEnd { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual Word Word { get; set; }

        
    }
}
